### ISSUE TITLE
samenvatting chapter 4/13/14

### ISSUE THREAD

**Issue by BoNaomiHeins** [cmda-bt/fe-course-20-21#1]
- Chapter 4:   Datastructures: Objects and Arrays
De array in JS is specifiek bedoelt om lijst met waarden op te slaan tussen []. Het eerste element in de array heeft de index 0. Bijna alle JavaScript-waarden hebben eigenschappen. De uitzonderingen zijn nullen undefined. 
De twee belangrijkste manieren om toegang te krijgen tot eigenschappen in JavaScript zijn met een punt en met vierkante haken. value.x -> is het woord achter de punt de letterlijke naam van de eigenschap. value[x] -> wordt de uitdrukking tussen de haken geëvalueerd om de eigenschap naam te krijgen.
Eigenschappen die functies bevatten, worden over het algemeen methoden genoemd met de waarde waartoe ze behoren, zoals in " toUpperCase een methode van een string".
Een stack, bij het programmeren, is een datastructuur waarmee je waarden erin kunt duwen en ze er weer uit kunt halen in de omgekeerde volgorde, zodat het ding dat als laatste is toegevoegd, eerst wordt verwijderd.
Waarden van het type object zijn willekeurige verzamelingen van properties. Een manier om een ​​object te maken, is door accolades als uitdrukking te gebruiken.
Correlatie is een maat voor de afhankelijkheid tussen statistische variabelen. Een statistische variabele is niet helemaal hetzelfde als een programmeervariabele. In statistieken heb je meestal een reeks metingen , en elke variabele wordt voor elke meting gemeten. Correlatie tussen variabelen wordt meestal uitgedrukt als een waarde die varieert van -1 tot 1. Nulcorrelatie betekent dat de variabelen niet gerelateerd zijn. Een correlatie van één geeft aan dat de twee perfect verwant zijn - als je er een kent, ken je ook de ander. Een negatieve betekent ook dat de variabelen perfect met elkaar verband houden, maar dat ze tegenpolen zijn - als de ene waar is, is de andere onwaar.

- Chapter 13: Javascript and the browser
verbinding van machines over de hele wereld is een netwerk dat internet wordt genoemd. de communicatie tussen twee computers gaat door middel van een reeks bits. De reeks bits hangt af van wat het probeert uit te drukken en van het gebruikte coderingsmechanisme. Een netwerkprotocol beschrijft een communicatiestijl via een netwerk. Het Hypertext Transfer Protocol (HTTP) is bijvoorbeeld een protocol voor het ophalen van benoemde bronnen.
Een TCP-verbinding werkt met poortnummers, De luistercomputer wordt de server genoemd en de verbindende computer wordt de client genoemd. Als de doelcomputer kan worden bereikt en op die poort luistert, is de verbinding tot stand gebracht.
Het World Wide Web is een reeks protocollen en formaten waarmee we webpagina's in een browser kunnen bezoeken. hoeft u alleen maar een machine op internet aan te sluiten en hem te laten luisteren op poort 80 met het HTTP-protocol, zodat andere computers hem om documenten kunnen vragen. Elk document op het web wordt genoemd door een Uniform Resource Locator (URL). Machines die met internet zijn verbonden, krijgen een IP-adres die verbonden is met een domeinnaam.  Eerst moet uw browser weten naar welk adres eloquentjavascript.net verwijst. Vervolgens maakt het, met behulp van het HTTP-protocol, een verbinding met de server op dat adres en vraagt ​​het naar de bron /13_browser.html .
sandboxing is het isoleren van een programmeeromgeving, met het web kunt u er doorheen kunt bladeren zonder alle pagina's die u bezoekt te vertrouwen.

- Chapter 14: The Document Object Model
de gegevenstructuur die de browser gebruikt om de documenten weer te geven heet het Document Object Model (DOM). Deze vorm is typerend voor geneste structuren waarbij elementen subelementen kunnen bevatten die op zichzelf lijken. We noemen een datastructuur een boom als deze een vertakte structuur heeft, geen cycli heeft (een knoop mag zichzelf niet bevatten, direct of indirect), en een enkele, goed gedefinieerde wortel heeft . In het geval van de DOM, dient als root.document.documentElement. Elk DOM-knooppuntobject heeft een nodeType eigenschap die een code (nummer) bevat die het type knooppunt identificeert. 
U kunt zich overal in de boomstructuur verplaatsen door alleen parents en child links te gebruiken. Maar JavaScript geeft u ook toegang tot een aantal extra gemakkelijke links. De firstChilden lastChild eigenschappen wijzen op de eerste en laatste kind elementen. Net als previousSiblingen nextSibling, dit zijn knooppunten met dezelfde ouder die direct voor of na het knooppunt zelf verschijnen. Voor previousSiblingis heeft het eerste kind de waarde nul, en bij nextSibling heeft het laatste kind de waarde nul.
Alle elementknooppunten hebben een getElementsByTagNamemethode die alle elementen met de gegeven tag naam verzamelt die afstammelingen zijn (directe of indirecte kinderen) van dat knooppunt en ze retourneert als een array achtig object. Om een ​​specifiek enkel knooppunt te vinden, kunt u het een attribute geven en in plaats daarvan gebruiken document.getElementById.
Je kan de DOM strucutuur ook aanpassingen doen. Om een child toe te voegen -> appendChild (zit het aan het einde van de child list. Of insertBefore, kan je de plek in de lijst bepalen. 
Je kan ook de methode replaceChild gebruiken om twee childs met elkaar om te ruilen van plek. 
elt: maakt een element node en de rest van zijn argumenten behandelt als onderliggende elementen van dat knooppunt. Deze functie wordt vervolgens gebruikt om er een ​​attributie aan toe te voegen.
je kan niet alleen met JS de pagina interactief maken maar ook de layout bepallen en de styling maken. En je kan een animatie maken, door middel van requestAnimationFrame. Browsers werken hun weergave niet bij terwijl een JavaScript-programma actief is, en staan ​​geen interactie met de pagina toe. Dit is waarom we het nodig hebben requestAnimationFrame, het laat de browser weten dat we voorlopig klaar zijn.

**Comment by MarvinMichel** [comment]
Helemaal top Bo! Zo te zien is de stof allemaal duidelijk.😊
