### ISSUE TITLE
Week 1: summaries

### ISSUE THREAD

**Issue by KaivWezel** [cmda-bt/fe-course-20-21#10]
# Chapter 4:   Datastructures: Objects and Arrays

In javascript most values have properties, exception being null and undefined.
Objects and arrays both are a form of object. Both values have properties which you can access:

- Value.property
- Value[property]

### Arrays
An array is an sequence of values. You can compare it with a list. You can loop over the values using a forEach loop.

### Objects
Objects are a type of value which can hold other values. This way you can group related information to have easy access at a later point.

# Chapter 13: Javascript and the browser

A network is easily created by connecting two computers and let them send data to each other. Since internet has been invented, we are able to transfer data over the world via HTTP (Hypertext Transfer Protocol). 

### www
Since the World Wide Web was launched people used browsers to visit different webpages. This is where the HTML and Javascript comes into play. HTML is the base of your website and you can link your javascript to it with the script tag. With javascript you can design interaction with your webpage.

### Browsers
Problem with browsers is that different browsers have different ways of processing information and that leaves us with incompatible platforms to visit our websites. Luckily browsers have become more uniform.

# Chapter 14: The Document Object Model
The document object model(DOM) is a way to visually interpret the HTML structure of you website. All the elements are structured like a tree, which means elements are nested in other elements. 

### Nodes
Every element is a node in the DOM tree. With javascript you can manipulate these nodes. By changing, adding or removing them from their parent node, you change the appearance of the webpage.

### Styling
By manipulating the DOM you can style the webpages just as you like. Add animations, color and interaction. The styling is done with CSS and can be done in javascript.

**Comment by MarvinMichel** [comment]
Hi Kai!
Je samenvatting ziet er prima uit. Het is wel erg beknopt, sommige onderwerpen mogen wel iets meer de diepte in. Misschien is het ook handig om wat code examples toe te voegen van bepaalde onderwerpen als references.👨‍💻
