### ISSUE TITLE
samenvattingen

### ISSUE THREAD

**Issue by jellekitz** [cmda-bt/fe-course-20-21#2]
- Chapter 4:   Datastructures: Objects and Arrays

**Data sets**
Javascript heeft een oplossing voor het opslaan van reeksen waarden, ook wel een array genoemd. Een array bestaat uit twee blok haken en waardes gescheiden door een komma.

De eerste index van een array is nul, niet één. Zero-based counting genaamd.

**Properties**
Bijna alle JavaScript waarden hebben eigenschappen. De uitzonderingen zijn nullen undefined.

De twee belangrijkste manieren om toegang te krijgen tot eigenschappen in JavaScript zijn:

- Door middel van een .
- Door middel van een []

De elementen van een array worden als "property" weergeven.

De "length" property geeft aan hoeveel elementen er in de array zitten.

**Methods**
Properties die functies bevatten, worden over het algemeen methods genoemd met de waarde waartoe ze behoren.

Een "stack", in programmeren, is een data structuur dat je waardes in en uit een array kan laten pushen.

**Objects**
Een manier om een ​​object te maken, is door accolades als uitdrukking te gebruiken. Tussen de accolades staat een lijst met eigenschappen, gescheiden door komma's. Elke eigenschap heeft een naam gevolgd door een dubbele punt en een waarde.

Om erachter te komen welke eigenschappen een object heeft, kan je de Object.keysfunctie gebruiken. Je geeft het een object en het retourneert een reeks strings oftewel de eigenschapsnamen van het object.

Er is een Object.assign functie die alle eigenschappen van het ene object naar het andere kopieert.

Arrays zijn dus gewoon een soort object dat gespecialiseerd is in het opslaan van reeksen dingen.

**Mutability**
getallen, tekenreeksen en Booleans, zijn allemaal onveranderlijk - het is onmogelijk om waarden van die typen te wijzigen.

Je gebruikt een let binding om een ​​veranderend getal bij te houden. Een const binding kan zelf niet worden gewijzigd, deze is constant.

Wanneer je objecten vergelijkt met de JavaScript == operator, vergelijkt het op identiteit: het zal alleen true produceren als beide objecten precies dezelfde waarde hebben.

- Chapter 13: Javascript and the browser

**Networks and the Internet**
Computernetwerken bestaan ​​al sinds de jaren vijftig. In de jaren tachtig werd er een manier verzonnen om gegevens tussen computers te versturen, dit werd het internet genoemd.

Een netwerkprotocol beschrijft een communicatiestijl via een netwerk. Er zijn protocollen voor het verzenden van e-mail, voor het ophalen van e-mail, voor het delen van bestanden enz.

Het Hypertext Transfer Protocol (HTTP) is een protocol voor het ophalen van benoemde bronnen (stukjes informatie, zoals webpagina's of afbeeldingen).

Een TCP-verbinding (Transmission Control Protocol) werkt als volgt: de ene computer moet wachten of luisteren voordat andere computers ermee beginnen te praten. Om te kunnen luisteren naar verschillende soorten communicatie tegelijkertijd, heeft elke "luisteraar" een nummer (een poort genaamd) die eraan is gekoppeld. De luistercomputer wordt de server genoemd en de verbindende computer wordt de client genoemd.

**The Web**
Het World Wide Web is een reeks protocollen en indelingen waarmee we webpagina's in een browser kunnen bezoeken. Elk document op het web wordt genoemd door een Uniform Resource Locator (URL).

Machines die met internet zijn verbonden, krijgen een IP-adres , een nummer dat kan worden gebruikt om berichten naar die machine te sturen

**HTML**
HTML staat voor Hypertext Markup Language en is het documentformaat dat wordt gebruikt voor webpagina's. HTML bestaat uit tekst en tags < >. Deze tags dienen bijna allemaal te worden afgesloten op een paar na als ze niks omsluiten. Een HTML bestand bestaat uit een , en een .

**HTML and JavaScript**
Door middel van een <script> tag kan je JavaScript direct in een HTML bestand zetten. Het is ook mogelijk om via deze tag een extern bestand te koppelen.

**In the sandbox**
Het isoleren van een programmeeromgeving wordt sandboxing genoemd, waarbij het idee is dat het programma onschadelijk in een sandbox speelt.

- Chapter 14: The Document Object Model

De browser bouwt een model op van de structuur van het HTML document en gebruikt dit model om de pagina op het scherm te tekenen. Deze weergave wordt het Document Object Model of afgekort DOM genoemd. Dit word vaak vergeleken met een boom (syntaxtree). De DOM word ook wel de taal neutrale interface genoemd omdat het in meerdere talen de "standaard" is.

DOM-knooppunten (nodes) bevatten veel links naar andere nabijgelegen knooppunten. elk knooppunt heeft een parentNodeeigenschap die verwijst naar het knooppunt waar het deel van uitmaakt, indien aanwezig. Je kan door middel van getElementsByTagName en getElementsByClassName de knooppunten beïnvloeden.

Vrijwel alles over de DOM-datastructuur kan worden gewijzigd. De vorm van de documentboom kan worden gewijzigd door parent & child relations te wijzigen. Knooppunten hebben een removemethode om ze uit hun huidige bovenliggende knooppunt te verwijderen.

Het is mogelijk om nieuwe knooppunten te maken door middel van document.createTextNode.

Sommige element kenmerken, zoals href voor links, zijn toegankelijk via een eigenschap met dezelfde naam op het DOM-object van het element. Dit is het geval voor de meest gebruikte standaardattributen.

Er bestaan inline en blok elementen. Voorbeelden van inline elementen zijn bijvoorbeeld a & strong en voor blok elementen zijn dit p & h1. Blok elementen blijven op dezelfde regel hangen terwijl inline elementen naar een volgende regel springen.

Een style-attribuut kan één of meer declaraties bevatten, die een eigenschap (zoals color) zijn, gevolgd door een dubbele punt en een waarde (zoals groen). Als er meer dan één aangifte is, moeten ze worden gescheiden door puntkomma's, zoals in "color: red; border: none".

Het stylingsysteem voor HTML wordt CSS genoemd, voor Cascading Style Sheets. Een stylesheet is een set regels voor het stylen van elementen in een document. Het kan in een <style> tag worden gegeven of in een extern bestand.

**Comment by MarvinMichel** [comment]
Prima samenvatting Jelle. Misschien is het handig om tussendoor wat code voorbeeldjes toe te voegen als geheugensteuntjes. Maar dat is een suggestie, geen must!😉
