### ISSUE TITLE
Week 1: Chapter summaries

### ISSUE THREAD

**Issue by Nino-dev** [cmda-bt/fe-course-20-21#34]
### Arrays

Binnen javascript kun je gebruik maken van arrays voor het opslaan van data. Een array moet je zien als een kast met verschillende lades waar per lade een ander object zit. 

**Voorbeeld van een array in JS:**

```
let listOfNumbers = [2, 3, 5, 7, 11];
```

Je kunt 1 van de items binnen de array uit lezen door hem in de console aan te roepen.

Een array begint bij 0, dus als je het eerste item wilt aanroepen gaat dit als volgt:

```
console.log(listOfNumbers[0]);
```

Daarnaast is het ook belangrijk dat je bij het declareren van een array gebruikt van de blokhaken []. 

Aan een array object hangen een aantal voorgeschreven properties. Deze kun je direct op de array aanroepen en toepassen. Mocht je bijvoorbeeld de lengte van een array willen (hoeveel items er in zitten) uitlezen is dit mogelijk met de volgende regel:

```
listOfNumbers.length; 
```

### Methods

Properties die over functies beschikken worden methods genoemd. Zo is “toUpperCase” een method die je op een string kunt aanroepen. Met deze methods zorg je ervoor dat de string in hoofdletters weergegeven wordt. 

### Objects

Binnen een object kun je verschillende data types opslaan. Leeftijd = number, naam = string etc. Je kunt het zien als een collectie van eigenschappen.  Met braces {} kun je een object declareren met hierbinnen de eigenschappen. 

**Voorbeeld:** 
```
let day1 = {
  squirrel: false,
  events: ["work", "touched tree", "pizza", "running"]
};
```

De waardes van objecten kunnen gemodificeerd worden. Numbers, strings etc zijn onveranderlijk. 

Ieder object heeft zijn eigen id. Dit betekend dat 2 verschillende objecten met dezelfde waarde niet gelijk aan elkaar staan.

### Loops

Een loop die itereert over een array: 

```
for (let i = 0; i < JOURNAL.length; i++) {
  let entry = JOURNAL[i];
  // Do something with entry
}
```

### HTTP

HTTP staat voor Hypertext Transfer Protocol en gebruikt om informatie te versturen of op te halen binnen het web. Denk hierbij aan het versturen van data in een formulier of het ophalen van een webpagina die je in de browser zoekbalk getypt hebt. 

```
GET /index.html HTTP/1.1
```
Boven
staand voorbeeld is een GET request die een webpagina ophaalt. Je hebt meerdere soorten requests waaronder POST waar je bijv. een formulier mee kunt versturen. 

### WWW

Het World Wide Web is een reeks aan protocollen en waarmee je webpagina's in een browser kunt bezoeken. Elk document op het web wordt genoemd door een Uniform Resource Locator (URL). Een URL bestaat uit een protocol (http/https) een server en een path.

### HTML/JavaScript 

Hypertext Markup Language (HTML) wordt gebruikt om webpagina's op te stellen. Een HTML-document bevat elementen die de structuur van het document opmaken: headings, tekst, secties etc.

In combinatie met JavaScript kan je ervoor zorgen dat een webpagina interactieve/dynamische elementen krijgt. JavaScript kun je toepassen binnen een HTML pagina door het extern aan te roepen vanuit een JS file of aan het einde van de body een <script> tag te gebruiken waarin de JS zich bevindt. 

## Chapter 14: The Document Object Model

Wanneer je een webpagina opent in de browser creëert de browser een Document Object Model (DOM). Dit model is opgebouwd als een verzameling van objecten die verwijzen naar HTML tags.

Je kunt de DOM zien als een boom die is opgebouwd uit verschillende nodes. De nodes zijn aftakking vanaf de root, oftewel de children. Deze child elementen kunnen ook weer children hebben: nesting. 
Elke datastructuur die een tree wordt genoemd heeft een root. In de DOM is de document.documentElement de root.

Je kunt de DOM direct manipuleren met JavaScript. 

### Bronnen

* Haverbeke, M. (2018). Data Structures: Objects and Arrays [E-book]. In Eloquent JavaScript: Vol. ISBN-13: 9781593279509 (3rd edition, p. 4). No Starch Press. https://eloquentjavascript.net/04_data.html
* Haverbeke, M. (2018). JavaScript and the Browser [E-book]. In Eloquent JavaScript: Vol. ISBN-13: 9781593279509 (3rd edition, p. 13). No Starch Press. https://eloquentjavascript.net/13_browser.html
* Haverbeke, M. (2018). The Document Object Model [E-book]. In Eloquent JavaScript: Vol. ISBN-13: 9781593279509 (3rd edition, p. 14). No Starch Press. https://eloquentjavascript.net/14_dom.html

**Comment by MarvinMichel** [comment]
Hoi Nino!
Goede samenvatting! Heel slim dat je wat code voorbeelden erbij hebt gedaan.🤓
