### ISSUE TITLE
Chapter 4, 13, 14 summary

### ISSUE THREAD

**Issue by lottekoblens** [cmda-bt/fe-course-20-21#5]
- Chapter 4:   Datastructures: Objects and Arrays
**Data structures** bestaan uit nummers, booleans en strings. 
**Objecten** laten ons waarden groeperen om zo complexere structuren te kunnen bouwen. Waarden van een object zijn eigenlijk willekeurige eigenschappen. Voorbeeld:  let descriptions = {
  work: "Went to work",
  "touched tree": "Touched a tree"
};

**Array:** een array is een gegevenstype die specifiek bedoelt is voor het opslaan van een reeks van waarden. Bij een array begin je met tellen vanaf 0. Dus de eerste waarde van de array roep je zo aan array[0]. Voorbeeld: let listOfNumbers = [2, 3, 5, 7, 11];

**Properties** zijn de waarden van een object. Om toegang te krijgen tot deze waarden gebruik je een punt of []. Bv. Value.color of value[x].

**Methods** zijn properties die functies bevatten.

**Let** kan veranderen, **const** kan niet veranderen.
De waarde in een const kan wel verandert worden. const score = {visitors: 0, home: 0};
// This is okay
score.visitors = 1;
// This isn't allowed
score = {visitors: 1, home: 1};

**Correlatie** is een maat voor de afhankelijkheid tussen statische variabelen. Correlatie tussen variabelen wordt meestal uitgedrukt als een waarde tussen -1 en 1. 0 betekent dat de variabelen geen relatie hebben. 1 betekent dat ze wel een relatie hebben en -1 betekent dat het tegenpolen zijn.

**Array loops:**
for (let i = 0; i < JOURNAL.length; i++) {
  let entry = JOURNAL[i];
  // Do something with entry
}
Wanneer i=0 en I is kleiner dan journal.length, dan wordt het uitgevoerd en wordt er 1 aan i toegevoegd.
Dit kan ook zo geschreven worden:
for (let entry of JOURNAL) {
  console.log(`${entry.events.length} events.`);
}
Hierbij zal de for loop de elementen van de waarde na of doorlopen.

Push en pop verwijderen of voegen elementen toe aan het eind van een array. Shift en task zijn methodes om dingen toe te voegen of te verwijderen aan de start van een array.
Een andere array methode is slice, die start- en eindindices gebruikt en een array retourneert met alleen de elementen ertussen.

Waarden van het type string, number en boolean zijn geen objecten. Als je hier properties aan toe wilt toevoegen, dan worden deze niet daadwerkelijk opgeslagen. Deze waarden zijn onveranderlijk en kunnen niet worden gewijzigd. Maar deze typen hebben wel ingebouwde eigenschappen en methoden, zoals slice en indexOf. 

Het kan handig zijn als een functie een willekeurig aantal argumenten accepteert. Om zo’n functie te schrijven plaats je 3 punten voor de laatste parameter van de functie:
function max(...numbers) {
  let result = -Infinity;
  for (let number of numbers) {
    if (number > result) result = number;
  }
  return result;
}
console.log(max(4, 1, 9, -2));

**Math object:** 
Nummer gerelateerde functies, zoals math.max.

**JSON**
Wordt veel gebruikt als een gegevensopslag- en communicatieformaat op internet. JSON lijkt op de manier waarop Javascript arrays en objecten schrijft, maar heeft een paar beperkingen. Alle property names moeten in “” staan.

- Chapter 13: Javascript and the browser
Een computer kan het internet gebruiken om bits naar een andere computer te sturen. Maar beide computers moeten dan wel weten wat deze bits representeren om ook daadwerkelijk te communiceren. 
Een netwerkportocol beschrijft de communicatiestijl via een netwerk. Zo heb je bijvoorbeeld een protocol voor het verzenden van e-mail, het ophalen van e-mail en het delen van bestanden.

Het **HTTP-protocol** is een protocol voor het ophalen van bronnen. Het specificeert eigenlijk dat de kant die het verzoek doet, moet beginnen met zo’n regel:
GET/index.html HTTP/1.1

**TCP(Transmission Control Protocol)-verbinding:** de ene computer moet wachten/luisteren voordat andere computers ermee kunnen gaan praten. Om te luisteren naar verschillende soorten communicatie tegelijkertijd op een enkele machine, moet zo’n luisteraar een poort hebben. Bij de meeste protocollen wordt gespecificeerd welke poort er standaard gebruikt moet worden. Een andere computer kan dan een verbinding tot stand brengen. Dit gebeurt door verbinding te maken met de target machine met behulp van het juiste poortnummer. 
Wanneer dan de target machine kan worden bereikt en luistert op de juiste poort dan is de verbinding tot stand gebracht. De listening computer is de **server** en de verbindende computer is de **client**.

De **World Wide Web** is eigenlijk een reeks van protocollen en indelingen waarmee wij mensen webpagina’s in een browser kunnen bezoeken. Om deel uit te maken van het web moet je een machine op het internet aansluiten en deze laten luisteren op poort 80 met het HTTP-protocol. Elk document is benoemd met een Uniform Resource Locator (URL): http://eloquentjavascript.net/13_browser.html. Het eerste deel van de URL vertelt dat het HTTP-protocol wordt gebruikt. Het 2e deel identificeert van welke server het document wordt opgevraagd. Het laatste deel is een padtekenreeks die het specifieke document identificeert die we willen laden.

HTML is het document format dat wordt gebruikt voor webpagina’s. HTML en JavaScript kunnen worden gekoppeld met <script>.

**Sandboxing**: browsers beperken wat een JavaScript-programma kan doen. Er kan niet naar de bestanden op je computer worden gekeken en er kan ook niks gewijzigd worden wat niet in de webpagina is ingesloten.

- Chapter 14: The Document Object Model
Elk HTML-document heeft een head en een body. 
**Tree**: een datastructuur met een vertakte structuur, geen cycles heeft en maar 1 goed gedefinieerde root heeft. In de DOM situatie is _document.documentElement_ de root. Een typische tree heeft verschillenden soorten nodes (knooppunten). Applicatie nodes kunnen children hebben, maar identifiers en values zijn leaves of nodes zonder children. Voor de DOM geldt hetzelfde, de nodes voor elementen, die de HTML-tags vertegenwoordigen, bepalen de structuur van het document. Deze kunnen dan ook nog onderliggende nodes hebben. Voorbeeld node: _document.body_.
Elk DOM-node heeft een **nodeType** eigenschap, deze bevat een code (nummer) die voor het type node staat. Elementen hebben code 1, dit is een constante eigenschap  _Node.ELEMENT_NODE_. Code 3 staat voor een tekstgedeelte in het document: _Node.TEXT_NODE_. Reacties hebben code 8 _Node.COMMENT_NODE_.

Elke node heeft een eigenschap **parentNode** die verwijst naar de node waar het deel van uitmaakt. En zo’n node heeft dus een **childNode** eigenschap die dan weer verijst naar een soort van array object dat de children bevat. De children property bevat maar 1 type child.  Het is het makkelijkst om gebruik te maken van _getElementsByTagName_ of _getElementsByClassName_. Of _getElementById_ als het element een id heeft. Tekst nodes worden gemaakt met behulp van de methode _document.createTextNode_.

**Attributes**
Met HTML kan elk attribuut op een node worden ingesteld. Hierdoor kan er extra informatie in een document worden opgeslagen. Gebruik getAttribute en setAttribute om hiermee te kunnen werken.

Met JavaScript kan je de grootte en de positie van een element achterhalen. _offsetWidth_ en _offsetHeight_ geven je de ruimte die het element dus inneemt, in pixels. Met _getBoundingClientRect_ krijg je de positie van een element.

**CSS**
Met p > a {…} wordt deze style toegepast op alle direct children van de p. Met p a {..} wordt deze style toegepast op alle <a> tags binnen een p tag. 

**Query Selectors**
Met _querySelectorAll_ geeft een NodeList met alle elementen waarmee het overeen komt.t _querySelector_ geeft je het eerst matchende element.

**Position**
_Static_: element staat op zijn normale plaats in het document.
_Relative_: kan element nu top, left of right plaatsen ten opzichte van normale plaats.
_Absolute_: het element wordt verwijderd uit de normale flow van het document, het kan dus overlappen met andere elementen.

**Animation**
Met _requestAnimationFrame_ wordt de animatiefunctie uitgevoerd wanneer de browser als het ware klaar is om het scherm opnieuw te painten. De animatiefunctie roept dan opnieuw _requestAnimationFrame_ aan om de volgende update te gaan plannen. Wanneer dan de browser actief is, dan zorgt dit ervoor dat de updates ook gaan plaatsvinden met ongeveer een snelheid van 60 per seconde.

**Math.cos en Math.sin**
_Math.cos_ en _Math.sin_ zijn handig om punten te vinden die op een cirkel rond punt (0,0) met een straal van 1 liggen. Math.con geeft je het x-coördinaat van het punt dat overeenkomt met de gegeven positie en Math.sin geeft de y-coördinaat.

**Comment by MarvinMichel** [comment]
Ziet er goed uit Lotte! Kleine tip wat betreft GitHub: als je gebruikt maakt van backticks(`) kun je code toevoegen aan je tekst. 

Dan krijg je i.p.v. dit:
function max(...numbers) {
let result = -Infinity;
for (let number of numbers) {
if (number > result) result = number;
}
return result;
}
console.log(max(4, 1, 9, -2));

Dit:
```javascript
function max(...numbers) {
  let result = -Infinity;
  for (let number of numbers) {
    if (number > result) result = number;
  }
  return result;
}
console.log(max(4, 1, 9, -2));
```

Met één backtick krijg je inline-code, met drie krijg je een code-block. Ziet er een stuk leuker uit😋
